apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: app-ui
spec:
  # let HPA set replica count
  replicas:
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-ui
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig 
    name: app-ui
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
