{
 "title": "Paste Board Application",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "SLO #1",
   "type": "graph",
   "description": "95% of requests are successful and respond within 1 second (measured in 1 minute interval)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(istio_request_duration_seconds_bucket{destination_service_name=\"app-ui\", response_code!~\"5.*\", le=\"1\"}[1m])) / sum(increase(istio_requests_total{destination_service_name=\"app-ui\"}[1m]))",
     "legendFormat": "% of successful requests to the UI that returned within 1 second (1 min interval)"
    }
   ]
  },
  {
   "title": "SLO #2",
   "type": "graph",
   "description": "90% of requests are successful and respond within 500 milliseconds (measured in 1 minute interval)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(istio_request_duration_seconds_bucket{destination_service_name=\"app-ui\", response_code!~\"5.*\", le=\"0.5\"}[1m])) / sum(increase(istio_requests_total{destination_service_name=\"app-ui\"}[1m]))",
     "legendFormat": "% of successful requests to the UI that returned within 500ms (1 min interval)"
    }
   ]
  },
  {
   "title": "SLO #1 Error Budget",
   "type": "graph",
   "description": "SLO #1 has 5% failure threshold",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1.0 - sum(increase(istio_request_duration_seconds_bucket{destination_service_name=\"app-ui\", response_code!~\"5.*\", le=\"1\"}[1m])) / sum(increase(istio_requests_total{destination_service_name=\"app-ui\"}[1m]))\n",
     "legendFormat": "% of requests that breached SLO #1 (1 min interval)"
    }
   ]
  },
  {
   "title": "SLO #2 Error Budget",
   "type": "graph",
   "description": "SLO #1 has 10% failure threshold",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1.0 - sum(increase(istio_request_duration_seconds_bucket{destination_service_name=\"app-ui\", response_code!~\"5.*\", le=\"0.5\"}[1m])) / sum(increase(istio_requests_total{destination_service_name=\"app-ui\"}[1m]))\n",
     "legendFormat": "% of requests that breached SLO #2 (1 min interval)"
    }
   ]
  }
 ]
}