apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: workshop-install
spec:
  tracing:
    type: None
  telemetry:
    type: Mixer
  addons:
    grafana:
      enabled: true
      install: {}
    kiali:
      name: kiali
      enabled: false
      install: {}
    prometheus:
      enabled: true
